### ISSUE TITLE
Question about choosing appropriate distribution of translation and rotation in your paper.

### ISSUE THREAD

**Issue by MinJunKang** [tjiiv-cprg/EPro-PnP#58] opened 2023-03-14 14:25 UTC
Hello, thanks for your great work!

For the case of 6-DOF pose estimation, Angular Gaussian distribution is used for rotation and multivariate T distribution is used for the translation case. 

My questions are:

1. I understand the reason why we are using the angular gaussian distribution for rotation but I cannot find the intuition of using multivariate T distribution for translation. Is there any specific reason for this?

2. For question 1, if not, can I replace the multivariate T distribution with just the gaussian distribution? Can you give some tips for choosing the right distribution to represent rotation and translation?

Thanks in advance!

**Comment by Lakonik** [comment] 2023-04-01 08:45
duplicate of #5

**Closed by Lakonik** 2023-04-01 08:45 UTC
